import Head from 'next/head';
import { Hero } from '@/components/Hero';
import { AboutUsSection } from '@/components/AboutUsSection';
import { Banner } from '@/components/Banner';
import { SlideProps, Slideshow } from '@/components/Slideshow';
import { Section } from '@/components/Section';
import { GetStaticProps, NextPage } from 'next';
import { getLayoutProps } from '@/handlers/server';
import { Layout, LayoutProps } from '@/components/Layout';

export const getStaticProps: GetStaticProps = async (context) => {
  const result = await getLayoutProps(context);

  return result;
};

type HomePageProps = LayoutProps;

const Home: NextPage<HomePageProps> = (props) => {
  // console.log('propsy: ', props);

  const slidesData: SlideProps[] = [
    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },

    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },

    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },

    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },

    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },
  ];

  return (
    <>
      <Head>
        <title>MZTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout
          mainMenuLogo={props.mainMenuLogo}
          mainMenuContact={props.mainMenuContact}
          mainMenu={props.mainMenu}
          footerSocial={props.footerSocial}
          footerPolicy={props.footerPolicy}
          footerCopyright={props.footerCopyright}
        >
          <Hero
            image="/icons/homeHeroImg.png"
            alt="zdjęcie z tańczącymi ludźmi"
          ></Hero>

          <AboutUsSection />

          <Section heading="Wydarzenia">
            <Slideshow slides={slidesData} />
          </Section>

          <Banner />

          <Section heading="Aktualności">
            <Slideshow slides={slidesData} />
          </Section>
        </Layout>
      </main>
    </>
  );
};

export default Home;
