import Head from 'next/head';
import { GetStaticProps, NextPage } from 'next';
import { Layout } from '@/components/Layout';
// import { getLayoutProps } from '@/handlers/server';

// export const getStaticProps: GetStaticProps = async (context) => {
//   const result = await getLayoutProps(context);

//   return result;
// };

// type HomePageProps = LayoutProps;

const Home: NextPage = () => {
  // console.log('propsy: ', props);

  return (
    <>
      <Head>
        <title>MZTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout></Layout>
      </main>
    </>
  );
};

export default Home;
