import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Article } from '@/components/Article';
import { Hero } from '@/components/Hero';
import { AboutUsSection } from '@/components/AboutUsSection';
import { Banner } from '@/components/Banner';
import { SlideProps, Slideshow } from '@/components/Slideshow';
import { Section } from '@/components/Section';

const inter = Inter({ subsets: ['latin'] });

const Home: React.FC = () => {
  const slidesData: SlideProps[] = [
    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },

    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },

    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },

    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },

    {
      image: {
        src: '/icons/Rectangle.png',
        alt: 'Wydarzenie',
        width: 300,
        height: 300,
      },
      heading: 'Wydarzenie',
      date: '2023-07-26',
      link: {
        link: '/',
        text: 'Sprawdź',
      },
    },
  ];

  return (
    <>
      <Head>
        <title>MZTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Article>
          <Hero
            image="/icons/homeHeroImg.png"
            alt="zdjęcie z tańczącymi ludźmi"
          ></Hero>

          <AboutUsSection />

          <Section heading="Wydarzenia">
            <Slideshow slides={slidesData} />
          </Section>

          <Banner />

          <Section heading="Aktualności">
            <Slideshow slides={slidesData} />
          </Section>
        </Article>
      </main>
    </>
  );
};

export default Home;
