import Head from 'next/head';
import { Inter } from '@next/font/google';
import { Article } from '@/components/Article';
import { RegulationsSection } from '@/components/Domain/regultaions/RegulationsSection/RegulationsSection';

const inter = Inter({ subsets: ['latin'] });

const Regulations: React.FC = () => {
  return (
    <>
      <Head>
        <title>MZTS - Regulamin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Article>
          <RegulationsSection />
        </Article>
      </main>
    </>
  );
};

export default Regulations;
