import Head from 'next/head';
import { Inter } from '@next/font/google';
import { RegulationsSection } from '@/components/Domain/regultaions/RegulationsSection/RegulationsSection';
import { Layout } from '@/components/Layout';
import { GetStaticProps, NextPage } from 'next';
// import { getLayoutProps } from '@/handlers/server';

// const inter = Inter({ subsets: ['latin'] });

// export const getStaticProps: GetStaticProps = async (context) => {
//   const result = await getLayoutProps(context);

//   return result;
// };

// type RegulationsPageProps = LayoutProps;

const RegulationsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>MZTS - Regulamin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Layout
          mainMenuLogo={props.mainMenuLogo}
          mainMenuContact={props.mainMenuContact}
          mainMenu={props.mainMenu}
          footerSocial={props.footerSocial}
          footerPolicy={props.footerPolicy}
          footerCopyright={props.footerCopyright}
        >
          <RegulationsSection />
        </Layout> */}
      </main>
    </>
  );
};

export default RegulationsPage;
