import { Accordion } from '@/components/Accordion/Accordion';
import { AdminstrationPanelLayout } from '@/components/Domain/panel/AdministrationPanelLayout';
import { PanelSection } from '@/components/Domain/panel/PanelSection';
import {
  PANEL_SECTION_COMPONENT,
  PANEL_SECTION_HEADER,
  PANEL_SECTION_VARIANT,
} from '@/components/Domain/panel/PanelSection/PanelSection.data';
import { panelAccordionContent } from '@/data/panel.data';
import { NextPage } from 'next';
import Head from 'next/head';

const AdministrationPanelPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>MZTS - panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AdminstrationPanelLayout>
          <PanelSection
            headerComponent={PANEL_SECTION_HEADER.H2}
            component={PANEL_SECTION_COMPONENT.SECTION}
            header="FAQ"
            variant={PANEL_SECTION_VARIANT.WITHOUT_IMG}
          >
            <Accordion content={panelAccordionContent} />
          </PanelSection>
        </AdminstrationPanelLayout>
      </main>
    </>
  );
};

export default AdministrationPanelPage;
