import { CompetitorsDataType, CompetitorsTableHeadCellsType, VisibleCompetitorsDataType } from "./CompetitorsTable.types";

const competitorsTableHeadCells = [
    { id: 'id', label: 'Id', isNumeric: true },
    { id: 'givenName', label: 'Imię', isNumeric: false },
    { id: 'family-name', label: 'Nazwisko', isNumeric: false },
    { id: 'selectSex', label: 'Płeć', isNumeric: false },
    { id: 'class', label: 'Klasa', isNumeric: false },
    { id: 'license', label: 'Licencja', isNumeric: false },
    {
      id: 'membership-fee',
      label: 'Opłata',
      isNumeric: false,
    },
  ] as CompetitorsTableHeadCellsType;

  const competitorsDataRows = [{
    id: 1001,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000', 
    givenName: 'John',
    familyName: 'Doe',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'H',
    license: 'Brak aktualnej licencji',
    membershipFee: 'Niedotyczy',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1002,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Jane',
    familyName: 'Smith',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'H',
    license: 'Aktualna',
    membershipFee: 'Niedotyczy',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1003,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Michael',
    familyName: 'Johnson',
    selectSex: 'Kobieta',
    class: 'F',
    license: 'Aktualna',
    membershipFee: 'Nieopłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1004,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Emma',
    familyName: 'Brown',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'G',
    license: 'Brak aktualnej licencji',
    membershipFee: 'Niedotyczy',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1005,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Daniel',
    familyName: 'White',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'H',
    license: 'Aktualna',
    membershipFee: 'Opłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1006,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Olivia',
    familyName: 'Martinez',
    selectSex: 'Kobieta',
    class: 'F',
    license: 'Brak aktualnej licencji',
    membershipFee: 'Nieopłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1007,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'William',
    familyName: 'Johnson',
    selectSex: 'Kobieta',
    class: 'G',
    license: 'Aktualna',
    membershipFee: 'Opłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1008,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Sophia',
    familyName: 'Davis',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'H',
    license: 'Aktualna',
    membershipFee: 'Opłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1009,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Alexander',
    familyName: 'Brown',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'F',
    license: 'Brak aktualnej licencji',
    membershipFee: 'Nieopłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1010,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Emily',
    familyName: 'Anderson',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'G',
    license: 'Aktualna',
    membershipFee: 'Opłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1011,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'James',
    familyName: 'Thomas',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'H',
    license: 'Brak aktualnej licencji',
    membershipFee: 'Niedotyczy',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1012,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Ava',
    familyName: 'Wilson',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'H',
    license: 'Aktualna',
    membershipFee: 'Opłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1013,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Benjamin',
    familyName: 'Moore',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'F',
    license: 'Brak aktualnej licencji',
    membershipFee: 'Nieopłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1014,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Mia',
    familyName: 'Johnson',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'G',
    license: 'Aktualna',
    membershipFee: 'Opłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1015,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Ethan',
    familyName: 'Miller',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'H',
    license: 'Aktualna',
    membershipFee: 'Opłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },
  {
    id: 1016,
    email: 'john@gmail.com',
    phoneNumber: '+48 000 000 000',  
    givenName: 'Abigail',
    familyName: 'Clark',
    careGiversName: 'adam Clark',
    selectSex: 'Mężczyzna',
    class: 'F',
    license: 'Aktualna',
    membershipFee: 'Opłacono',
    sportClub: 'AZTS Gdańsk',
    pairId: false,
  },] as CompetitorsDataType[]

  const INVISIBLE_VALUES = {
    EMAIL: 'email',
    PHONE_NUMBER: 'phoneNumber',
    CAREGIVERS_NAME: 'careGiversName',
    SPORT_CLUB: 'sportClub',
    PAIR_ID: 'pairId',
  } as const;

  // const invisibleValues = Object.values(INVISIBLE_VALUES) as string[];

  const visibleCompetitorsDataRows = (array: CompetitorsDataType[]): VisibleCompetitorsDataType[] => array.map(({ email, phoneNumber, careGiversName, sportClub, pairId, ...current}) => {
    return current;
  })

  export { competitorsTableHeadCells, competitorsDataRows, visibleCompetitorsDataRows, INVISIBLE_VALUES}